begup/begup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
#Import Extras
import debug_toolbar

#Definimos todas nuestra roots:
urlpatterns = [
    #Standard
    path('admin/', admin.site.urls),

    #Admin-User Paths
    url(r'^login/$',auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),

    #Extras
    url(r'^tinymce/', include('tinymce.urls')),
    #path('backup/', include('backups.urls', namespace='bkups')),

    #Debug:
    path('__debug__/', include(debug_toolbar.urls)),

    #Apps:
    path('', include('core.urls')),
    path('georef/', include('georef.urls')),
    path('noticias/', include('noticias.urls')),
    path('beneficiarios/', include('beneficiarios.urls')),
    path('empresas/', include('empresas.urls')),
    path('establecimientos/', include('establecimientos.urls')),
    path('contenidos/', include('contenidos.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

begup/core/urls.py
#Imports de Django
from django.conf.urls import url
from django.urls import path
#Imports de la app
from . import views
from . import autocomplete

#Definimos nuestros Paths
app_name = 'core'
urlpatterns = [
    #Home
    url(r'^$', views.home, name='home'),
    path('faqs', views.faqs, name='faqs'),
    path('contacto', views.contacto, name='contacto'),
    
    #Acceso de usuarios
    path('login', views.home_login, name='home_login'),
    path('logout', views.home_logout, name='home_logout'),
    
    #Administracion de usuarios
    path('user/admin_usuarios/<str:app_name>', views.admin_usuario, name='admin_usuario'),
    path('user/crear_usuario/<str:app_name>', views.crear_usuario, name='crear_usuario'),
    path('user/mod_usuario/<str:app_name>/<int:admin_id>', views.modificar_usuario, name='modificar_usuario'),
    path('user/mod_password/<str:app_name>/<int:user_id>', views.cambiar_password, name='cambiar_password'),
    path('user/des_user/<str:app_name>/<int:user_id>', views.desactivar_usuario, name='desactivar_usuario'),
    path('user/act_user/<str:app_name>/<int:user_id>', views.activar_usuario, name='activar_usuario'),
    
    #Administrar Roles
    path('grupos/<str:app_name>', views.configurar_grupos, name='configurar_grupos'),
    path('grupos/<str:app_name>/add', views.crear_grupo, name='crear_grupo'),
    path('grupos/<str:app_name>/delete/<int:grupo_id>', views.delete_grupo, name='delete_grupo'),

    #Auditoria
    path('auditoria', views.auditoria, name='auditoria'),
    path('auditoria/<int:user_id>', views.auditoria, name='auditoria_propia'),
    path('auditar/obj/<int:content_id>/<int:object_id>', views.auditar_cambios, name='auditar_cambios'),

    #Validaciones:
    url(r'^act_usuario/(?P<usuario_id>[0-9]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activar_usuario_mail, name='activar_usuario_mail'),
    url(r'^act_consulta/(?P<consulta_id>[0-9]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activar_consulta, name='activar_consulta'),
    
    #Autocomplete
    url(r'^usuarios-autocomplete/$', autocomplete.UsuariosAutocomplete.as_view(), name='usuarios-autocomplete',),

    #Web Services
    path('ws/', views.ws, name='ws'),
    path('ws/<str:nombre_app>/<str:nombre_modelo>/', views.ws, name='ws'),
]

begup/core/models.py
#Imports de python

#Imports django
from django.db import models
#Extra modules import
from tinymce.models import HTMLField
from auditlog.registry import auditlog
#Imports del proyecto
from begup.settings import DEBUG, LOADDATA
#Imports de la app
from .choices import TIPO_LOG

#Modelos
# Create your models here.
class Faq(models.Model):
    orden = models.IntegerField()
    pregunta = models.CharField('Titulo', max_length=200)
    respuesta = HTMLField()
    class Meta:
        ordering = ['orden']
    def __str__(self):
        return self.pregunta
    def as_dict(self):
        return {
            "id": int(self.id),
            "orden": int(self.orden),
            "pregunta": self.pregunta,
            "respuesta": self.respuesta,
        }

class Consulta(models.Model):
    autor = models.CharField('Nombre y Apellido', max_length=100)
    email = models.EmailField('Correo Electronico Personal')
    telefono = models.CharField('Telefono', max_length=50, blank=True, null=True)
    asunto = models.CharField('Asunto', max_length=100)
    descripcion = HTMLField()
    fecha_consulta = models.DateTimeField(auto_now_add=True)
    valida = models.BooleanField('Email Validado', default=False)
    def __str__(self):
        return self.autor + ": " + self.asunto + '(' + str(self.fecha_consulta.date()) + ')'

#Auditoria
auditlog.register(Faq)
#Señales
if not LOADDATA:
    from core.signals import enviar_mail_new_user

begup/core/views.py
#
#       HACER PRIORIDADES
#

#Un sistema de turno por día con un máximo de 360 turnos automáticamente repartidos en los horarios de 7:00 a 19:00

# modelo de feriados > restar a maximo de pasajes


#ARREGLAR:
# SISTEMA DE DESCUENTO DE PASAJES ES SUPER LENTO!!!

#Import Python Standard
import json
#Imports de Django
from django.apps import apps
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.contrib.auth import login, logout
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.contrib.auth.hashers import make_password
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.contenttypes.models import ContentType
from django.contrib.admin.views.decorators import staff_member_required
#Imports extras
from auditlog.models import LogEntry
#Imports de la app
from .models import Faq, Consulta
from .forms import ConsultaForm
from .forms import CrearUsuarioForm, ModUsuarioForm, ModPasswordForm, CrearRolForm, AuditoriaForm
from .functions import obtener_modeladmin, obtener_grupos, obtener_permisos, auditar_objeto
from .tokens import account_activation_token
from .decoradores import superuser_required, generic_permission_required

#Definimos las vistas
#PUBLICAS:
def home(request):
    return render(request, 'home.html', {})

def faqs(request):
    faqs_list = Faq.objects.all().order_by('orden')
    return render(request, 'faqs.html', {'faqs': faqs_list, })

def contacto(request):
    if request.method == 'POST': #En caso de que se haya realizado una busqueda
        consulta_form = ConsultaForm(request.POST)
        if consulta_form.is_valid():
            consulta = consulta_form.save()
            #enviar email de validacion
            to_email = consulta_form.cleaned_data.get('email')#Obtenemos el correo
            #Preparamos el correo electronico
            mail_subject = 'Confirma tu correo de respuesta por la Consultas Realizada al begup.'
            message = render_to_string('emails/acc_active_consulta.html', {
                    'consulta': consulta,
                    'token':account_activation_token.make_token(consulta),
                })
            #Instanciamos el objeto mail con destinatario
            email = EmailMessage(mail_subject, message, to=[to_email])
            #Enviamos el correo
            #email.send()
            return render(request, 'contacto.html', {})
    else:
        consulta_form = ConsultaForm()
    return render(request, 'contacto.html', {"form": consulta_form,
                'titulo': "Envianos una consulta:", 'boton': "Enviar"})

#Manejo de sesiones de Usuarios
def home_login(request):
    message = ''
    form = AuthenticationForm()
    if request.method == "POST":
        # Añadimos los datos recibidos al formulario
        form = AuthenticationForm(data=request.POST)
        # Si el formulario es válido...
        if form.is_valid():
            # Recuperamos las credenciales validadas
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            # Verificamos las credenciales del usuario
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return home(request)
    return render(request, "extras/generic_form.html", {'titulo': "Ingresar al Sistema", 'form': form, 'boton': "Ingresar", 'message': message, })

def home_logout(request):
    logout(request)
    return home(request)

#Sistema de manejo de Usuarios No staff
@generic_permission_required('administrador')
def admin_usuario(request, app_name):
    ModelAdmin = obtener_modeladmin(app_name)
    administradores = ModelAdmin.objects.all()
    #Casos particulares:
    if not request.user.is_superuser:
        if ModelAdmin.has_administrado():
            administrador = ModelAdmin.objects.get(usuario=request.user)
            administrado = ModelAdmin.get_administrado(administrador)
            administradores = ModelAdmin.filtrar(administradores, administrado)
    #Mandamos frula
    return render(request, "users/lista_usuarios.html", {
        'administradores': administradores, 
        'app_name': app_name,
        'administrado': ModelAdmin.has_administrado(),
        'has_table': True,
    })

@generic_permission_required('administrador')
def crear_usuario(request, app_name):
    ModelAdmin = obtener_modeladmin(app_name)
    if ModelAdmin.has_administrado():
        administrador = ModelAdmin.objects.get(usuario=request.user)
        administrado = ModelAdmin.get_administrado(administrador)
        if request.user.is_superuser:
            return redirect('/'+app_name.lower()+'/crear_admin')
        elif not administrado:
            return render(request, "extras/error.html", {'error': 'No se identifico asignacion del Usuario Creador'})
    #Comenzamos el proceso de creacion:
    form = CrearUsuarioForm(group_list=obtener_grupos(app_name))#Asignamos grupos especificos de la app
    if request.method == 'POST':
        form = CrearUsuarioForm(request.POST)
        if form.is_valid():
            #Primero creamos el usuario
            usuario = User(
                username = form.cleaned_data['username'],
                #password > Se genera en el envio del mail
                email = form.cleaned_data['email'],
                first_name = form.cleaned_data['nombre'],
                last_name = form.cleaned_data['apellido'],
            )
            usuario.save()
            #Le agregamos los roles elegidos:
            for grupo in request.POST.getlist('grupos'):
                usuario.groups.add(grupo)
            usuario.save()
            #Le asignamos organizacion del creador
            administrador = ModelAdmin()
            administrador.usuario = usuario
            if ModelAdmin.has_administrado():
                administrador.set_administrado(administrado)
            administrador.save()
            #Le agregamos los permisos
            return redirect('core:admin_usuario', app_name=app_name)
    return render(request, "extras/generic_form.html", {'titulo': "Crear Usuario:", 'form': form, 'boton': "Crear"})

@generic_permission_required('administrador')
def modificar_usuario(request, app_name, admin_id):
    grupos = obtener_grupos(app_name)
    ModelAdmin = obtener_modeladmin(app_name)
    administrador = ModelAdmin.objects.get(pk=admin_id)
    form = ModUsuarioForm(group_list=grupos,
        initial={
            'username': administrador.usuario.username,
            'email': administrador.usuario.email,
            'grupos': [g.id for g in administrador.usuario.groups.all()],
        })
    if request.method == 'POST':
        form = ModUsuarioForm(request.POST)
        if form.is_valid():
            administrador.usuario.email = form.cleaned_data['email']
            administrador.save()
            #Limpiamos roles para cargar los nuevos
            for grupo in grupos:
                administrador.usuario.groups.remove(grupo.id)
            for grupo in request.POST.getlist('grupos'):
                administrador.usuario.groups.add(grupo)
            administrador.usuario.save()
            return redirect('core:admin_usuario', app_name=app_name)
    #Sea por ingreso o por salida:
    return render(request, "extras/generic_form.html", {'titulo': "Modificar Usuario", 
        'form': form, 'boton': "Modificar",})

@generic_permission_required('administrador')
def cambiar_password(request, app_name, user_id):
    usuario = User.objects.get(pk=user_id)
    form = ModPasswordForm(initial={'username': usuario.username, })
    if request.method == 'POST':
        form = ModPasswordForm(request.POST)
        if form.is_valid():
            usuario.password = make_password(form.cleaned_data['passwd1'])
            usuario.save()
            return admin_usuario(request, app_name)
    #Sea por ingreso o por salida:
    return render(request, "extras/generic_form.html", {'titulo': "Modificar Usuario", 'form': form, 'boton': "Modificar", })

@generic_permission_required('administrador')
def desactivar_usuario(request, app_name, user_id):
    user = User.objects.get(pk=user_id)
    user.is_active = False
    user.save()
    return admin_usuario(request, app_name)

@generic_permission_required('administrador')
def activar_usuario(request, app_name, user_id):
    user = User.objects.get(pk=user_id)
    user.is_active = True
    user.save()
    return admin_usuario(request, app_name)

#Manejo de roles
@superuser_required
def configurar_grupos(request, app_name):
    grupos = obtener_grupos(app_name)
    permisos = obtener_permisos(app_name)
    if request.method == 'POST':
        for grupo in grupos:
            grupo.permissions.clear()
            for permiso in permisos:
                checkbox = str(grupo.id) + '-' + str(permiso.id)
                if checkbox in request.POST:
                    grupo.permissions.add(permiso)
            grupo.save()
    return render(request, "users/configurar_roles.html", {'grupos': grupos, 'permisos': permisos, 'app_name': app_name, })

@superuser_required
def crear_grupo(request, app_name):
    form = CrearRolForm(initial={'app_name': app_name, })
    if request.method == 'POST':
        form = CrearRolForm(request.POST)
        if form.is_valid():
            Group(name=form.group_name).save()
            return redirect('/grupos/'+app_name)
    return render(request, "extras/generic_form.html", {'titulo': "Crear Grupo de Permisos", 'form': form, 'boton': "Crear", })

@superuser_required
def delete_grupo(request, app_name, grupo_id):
    Group.objects.get(id=grupo_id).delete()
    return configurar_grupos(request, app_name)

#Auditoria
@staff_member_required
def auditoria(request, user_id=None):
    form = AuditoriaForm()
    if user_id:

begup/core/templates/users/auditoria.html
{% extends 'base/base.html' %}
{% load adminusers_tags %}
{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">        
                    <h1>Auditoria de: <b>{{usuario}}</b></h1>
                    <h3>Periodo: {{begda}} - {{endda}}</h3>
                    <div class="col-md-12">
                        <table class="listado">
                            <tr>
                                <th colspan="2">Objeto</th>
                                <th>Accion</th>
                                <th>Fecha</th>
                                <th>Cambios</th>
                            </tr>
                            {% for reg in registros %}
                                <tr>
                                    <td>{% ct_model_name reg %}</td>
                                    <td>{{reg.object_repr}}</td>
                                    <td>{{reg.get_action_display}}</td>
                                    <td>{{reg.timestamp}}</td>
                                    <td>
                                        <ul>
                                            {% ct_changes_to_list reg.changes as changes %}
                                            {% for change in changes %}
                                                <li>{{change}}</li>
                                            {% endfor %}
                                        </ul>
                                    </td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}   

begup/core/templates/users/configurar_roles.html
{% extends 'base/base.html' %}
{% load humanize %}
{% load static %}

{% block custom_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/user_management.css' %}" />
{% endblock %}

{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">
                    <br>      
                    <h2>Defina los permisos de cada rol
                        <a href="{% url 'core:crear_grupo' app_name=app_name %}">
                            <img class="iconsx2" src="{% static '/img/icons/add_role.png' %}" alt="Agregar Grupo">
                        </a>
                    </h2>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            {% for grupo in grupos %}
                                <div class="col-sm-4 grupo">
                                    <h3 class="grupo">{{grupo.name}}
                                    <a href="{% url 'core:delete_grupo' app_name=app_name grupo_id=grupo.id %}">
                                        <img class="icons" src="{% static '/img/icons/delete.png' %}" alt="Eliminar">
                                    </a>
                                </h3>
                               
                                {% for permiso in permisos %}
                                    <input type="checkbox" id="{{grupo.id}}-{{permiso.id}}" name="{{grupo.id}}-{{permiso.id}}" value="{{grupo.id}}-{{permiso.id}}"
                                        {% if permiso in grupo.permissions.all %}checked{% endif %}
                                    >
                                    <label for="{{grupo.id}}-{{permiso.id}}">{{permiso.name|title}}</label><br>
                                {% endfor %}
                                </div>
                            {% endfor %}
                        </div>
                        <div class="row">
                            <div class="col-sm-4"></div>
                            <div class="col-sm-4">
                                <button type="submit">Configurar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

begup/core/templates/users/lista_usuarios.html
{% extends 'base/base.html' %}
{% load adminusers_tags %}
{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">        
                    <h1>Listado de Usuarios: <b>{{app_name}}</b></h1>
                    <p style="float:right;">
                        {% if administrado and request.user.is_superuser %}
                            <a href="{% crear_link_addadmin app_name %}">
                                Crear Administrador General
                                <img class="icons" src="/static/admin/img/icon-addlink.svg" alt="Crear Nuevo Usuario">
                            </a>
                        {% else %}
                            <a href="{% url 'core:crear_usuario' app_name=app_name %}">
                                Crear Usuario
                                <img class="icons" src="/static/admin/img/icon-addlink.svg" alt="Crear Nuevo Usuario">
                            </a>
                        {% endif %}
                    </p>
                    <div class="col-md-12">
                        <table class="listado" id="table">
                            <thead>
                                <tr>
                                    <th>Usuario</th>
                                    <th>Nombre Completo</th>
                                    <th>Email</th>
                                    <th>Administra</th>
                                    <th>Roles</th>
                                    <th>Estado</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for admin in administradores %}
                                    <tr>
                                        <td>{{admin.usuario.username}}</td>
                                        <td>{{admin.usuario.last_name}}, {{admin.usuario.first_name}}</td>
                                        <td>{{admin.usuario.email}}</td>
                                        <td>
                                            {{admin.get_administrado}}
                                        </td>
                                        <td>
                                            <ul>
                                                {% for grupo in admin.usuario.groups.all %}
                                                    <li>{{grupo.name}}</li>
                                                {% endfor %}
                                            </td>
                                        <td>
                                            {% if admin.usuario.is_active %}
                                                <b style="color:green;">Activo</b>
                                            {% else %}
                                                <b style="color:red;">Inactivo</b>
                                            {% endif %}
                                        </td>
                                        <td>
                                            <a class="nolink" href="{% url 'core:modificar_usuario' app_name=app_name admin_id=admin.id %}">
                                                <img class="icons" src="/static/admin/img/icon-changelink.svg" alt="Modificar">
                                            </a>
                                            <a class="nolink" href="{% url 'core:cambiar_password' app_name=app_name user_id=admin.usuario.id %}">
                                                <img class="icons" src="/static/img/icons/changepassword.png" alt="Cambiar contraseña">
                                            </a>
                                            {% if admin.usuario.is_active %}
                                                <a class="nolink" href="{% url 'core:desactivar_usuario' app_name=app_name user_id=admin.usuario.id %}">
                                                    <img class="icons" src="/static/admin/img/icon-deletelink.svg" alt="Desactivar">
                                                </a>
                                            {% else %}
                                                <a class="nolink" href="{% url 'core:activar_usuario' app_name=app_name user_id=admin.usuario.id %}">
                                                    <img class="icons" src="/static/img/icons/check.png" alt="Activar">
                                                </a>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}   

begup/core/templates/users/login.html
{% extends 'base/base.html' %}

{% block custom_head %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/generic_form.css' %}" />
{% endblock %}

{% block content %}
    <section class="formulario">
        <section class="formulario-container">
                {% if user.is_authenticated %}
                    <form method="post" action="/">
                        {% csrf_token %}
                        <h1>Tu usuario no tiene acceso a esta seccion, por favor contacte al administrador.</h1>
                        <div class="input-group" style="margin:10px;">
                            <button class="btn btn-primary" type="submit">Regresar</button>
                        </div>
                    </form>
                {% else %}
                    <h2>Ingrese al sitio para tener acceso a la seccion requerida:</h2>
                    <form method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <label for="id_username">Usuario:</label><br>
                            <input type="text" class="form-control" name="username" autofocus maxlength="254" required id="id_username" /><br>
                        </div>
                        
                        <div class="input-group">
                            <label for="id_password">Contraseña:</label><br>
                            <input type="password" class="form-control" name="password" id="id_password" required /><br>
                        </div>
                        {% if form.errors %}
                            <p>Tu usuario y Contraseña son incorrectos, por favor intenta de nuevo.</p>
                        {% endif %}
                        <div class="input-group" style="margin:10px;">
                            <button class="btn btn-primary" type="submit">Ingresar</button>
                        </div>
                    </form>
                {% endif %}
        </section>
    </section>
{% endblock %}

begup/core/templates/users/no_perms.html
{% extends 'base/base.html' %}


{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container informacion_basica">
                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-6">
                        <h1>Intento Acceder a una seccion a la que no tiene permiso.</h1>
                        {% if error %}
                            <p>{{error}}</p>
                        {% endif %}
                        <a href="javascript:history.back()"><p>Vuelva a intentarlo</p></a>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}