begup/begup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
#Import Extras
import debug_toolbar

#Definimos todas nuestra roots:
urlpatterns = [
    #Standard
    path('admin/', admin.site.urls),

    #Admin-User Paths
    url(r'^login/$',auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),

    #Extras
    url(r'^tinymce/', include('tinymce.urls')),
    #path('backup/', include('backups.urls', namespace='bkups')),

    #Debug:
    path('__debug__/', include(debug_toolbar.urls)),

    #Apps:
    path('', include('core.urls')),
    path('georef/', include('georef.urls')),
    path('noticias/', include('noticias.urls')),
    path('beneficiarios/', include('beneficiarios.urls')),
    path('empresas/', include('empresas.urls')),
    path('establecimientos/', include('establecimientos.urls')),
    path('contenidos/', include('contenidos.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

begup/beneficiarios/urls.py
#Imports Django
from django.urls import path
from django.conf.urls import url
#Imports de la app
from . import views

app_name = 'beneficiarios'
urlpatterns = [
    #Home
    path('', views.menu, name='menu'),
    #Basicas del menu administrativo
    path('buscar/', views.buscar_beneficiario, name='buscar_beneficiario'),
    path('crear/', views.crear_beneficiario, name='crear_beneficiario'),
    path('resumen/<int:beneficiario_id>', views.resumen, name='resumen'),
    path('tarjeta/<int:beneficiario_id>', views.ver_tarjeta, name='ver_tarjeta'),
    path('modificar/<int:beneficiario_id>', views.modificar_beneficiario, name='modificar_beneficiario'),
    path('baja/<int:beneficiario_id>', views.baja_beneficiario, name='baja_beneficiario'),
    path('subir_foto/<int:beneficiario_id>', views.subir_fotografia, name='subir_fotografia'),
    path('crear_user/<int:beneficiario_id>',  views.crear_usuario_beneficiario, name='crear_usuario_beneficiario'),
    path('modpasswd/<int:user_id>',  views.mod_password_beneficiario, name='mod_password_beneficiario'),
    path('act_user/<int:user_id>',  views.activar_usuario_benef, name='activar_usuario_benef'),
    #Mod info
    path('mod_domicilios/<int:beneficiario_id>', views.modificar_domicilios, name='modificar_domicilios'),
    path('mod_educativa/<int:beneficiario_id>', views.modificar_info_educativa, name='modificar_info_educativa'),
    path('edu/historico/<int:educativa_id>', views.historico_educativo, name='historico_educativo'),
    #Manejo documentos
    path('documentos_pendientes', views.documentos_pendientes, name='documentos_pendientes'),
    path('docs/subir/<int:beneficiario_id>', views.subir_documentacion, name='subir_documentacion'),
    path('docs/activar/<int:doc_id>', views.activar_doc, name='activar_doc'),
    path('eliminar_doc/<int:doc_id>', views.eliminar_doc, name='eliminar_doc'),
    #Manejo de Creditos
    path('credito/pendientes', views.creditos_pendientes, name='creditos_pendientes'),
    path('credito/<int:credito_id>', views.ver_credito, name='ver_credito'),
    path('credito/historial/<int:beneficiario_id>', views.historial_creditos, name='historial_creditos'),
    path('credito/crear/<int:beneficiario_id>', views.crear_credito, name='crear_credito'),
    path('credito/editar/<int:credito_id>', views.editar_credito, name='editar_credito'),
    path('credito/aprobar/<int:credito_id>', views.aprobar_credito, name='aprobar_credito'),
    path('credito/eliminar/<int:credito_id>', views.baja_credito, name='eliminar_credito'),
    path('credito/baja/<int:credito_id>', views.baja_credito, name='baja_credito'),
    #Manejo de Tramos
    path('tramos/', views.lista_tramos, name='lista_tramos'),
    path('tramos/<int:tramo_id>', views.ver_tramo, name='ver_tramo'),
    path('tramos/crear/', views.crear_tramo, name='crear_tramo'),
    path('tramos/eliminar/<int:tramo_id>', views.eliminar_tramo, name='eliminar_tramo'),
    #Area de Beneficiarios
    path('pub/ingreso/', views.ingreso_beneficiario, name='ingreso_beneficiario'),
    path('pub_crear_credito/<int:beneficiario_id>', views.crear_credito, name='pub_crear_credito'),
    #path('pub_subir_documentacion/<int:beneficiario_id>', views.subir_documentacion, name='pub_subir_documentacion'),
    #path('pub_mod_beneficiario/<int:beneficiario_id>', views.modificar_beneficiario, name='pub_mod_beneficiario'),
    #path('pub_mod_domicilios/<int:beneficiario_id>', views.modificar_domicilios, name='pub_mod_domicilios'),
    #path('pub_mod_info_educativa/<int:beneficiario_id>', views.modificar_info_educativa, name='pub_mod_info_educativa'),
    #path('pub_subir_fotografia/<int:beneficiario_id>', views.subir_fotografia, name='pub_subir_fotografia'),
    #REPORTES
    path('rep/tarjetas/', views.tarjetas_impresas, name='tarjetas_impresas'),
    path('rep/creditos/', views.reporte_creditos, name='reporte_creditos'),
    url(r'down/creditos/(?P<begda>\d{4}-\d{2}-\d{2})/(?P<endda>\d{4}-\d{2}-\d{2})', views.download_creditos, name='download_creditos'),
    url(r'down/tarjetas/(?P<begda>\d{4}-\d{2}-\d{2})/(?P<endda>\d{4}-\d{2}-\d{2})', views.download_tarjetas, name='download_tarjetas'),
    #Carga Masiva
    path('upload', views.upload_beneficiarios, name='upload_beneficiarios'),
]

begup/core/urls.py
#Imports de Django
from django.conf.urls import url
from django.urls import path
#Imports de la app
from . import views
from . import autocomplete

#Definimos nuestros Paths
app_name = 'core'
urlpatterns = [
    #Home
    url(r'^$', views.home, name='home'),
    path('faqs', views.faqs, name='faqs'),
    path('contacto', views.contacto, name='contacto'),
    
    #Acceso de usuarios
    path('login', views.home_login, name='home_login'),
    path('logout', views.home_logout, name='home_logout'),
    
    #Administracion de usuarios
    path('user/admin_usuarios/<str:app_name>', views.admin_usuario, name='admin_usuario'),
    path('user/crear_usuario/<str:app_name>', views.crear_usuario, name='crear_usuario'),
    path('user/mod_usuario/<str:app_name>/<int:admin_id>', views.modificar_usuario, name='modificar_usuario'),
    path('user/mod_password/<str:app_name>/<int:user_id>', views.cambiar_password, name='cambiar_password'),
    path('user/des_user/<str:app_name>/<int:user_id>', views.desactivar_usuario, name='desactivar_usuario'),
    path('user/act_user/<str:app_name>/<int:user_id>', views.activar_usuario, name='activar_usuario'),
    
    #Administrar Roles
    path('grupos/<str:app_name>', views.configurar_grupos, name='configurar_grupos'),
    path('grupos/<str:app_name>/add', views.crear_grupo, name='crear_grupo'),
    path('grupos/<str:app_name>/delete/<int:grupo_id>', views.delete_grupo, name='delete_grupo'),

    #Auditoria
    path('auditoria', views.auditoria, name='auditoria'),
    path('auditoria/<int:user_id>', views.auditoria, name='auditoria_propia'),
    path('auditar/obj/<int:content_id>/<int:object_id>', views.auditar_cambios, name='auditar_cambios'),

    #Validaciones:
    url(r'^act_usuario/(?P<usuario_id>[0-9]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activar_usuario_mail, name='activar_usuario_mail'),
    url(r'^act_consulta/(?P<consulta_id>[0-9]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activar_consulta, name='activar_consulta'),
    
    #Autocomplete
    url(r'^usuarios-autocomplete/$', autocomplete.UsuariosAutocomplete.as_view(), name='usuarios-autocomplete',),

    #Web Services
    path('ws/', views.ws, name='ws'),
    path('ws/<str:nombre_app>/<str:nombre_modelo>/', views.ws, name='ws'),
]

begup/beneficiarios/views.py
#Imports de Python
import csv
import string
from datetime import date
#Imporst Extras
from auditlog.models import LogEntry
#Imports de Django
from django.utils import timezone
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.decorators import permission_required
#Imports del proyecto
from begup.constantes import NOMAIL, LAST_DATE
from georef.models import Localidad
from core.forms import UploadFotoForm
from core.forms import CrearUsuarioForm, ModUsuarioForm, ModPasswordForm
from core.forms import CrearRolForm, AuditoriaForm
from core.forms import FechaForm, PeriodoForm
from core.functions import paginador
from core.functions import instace_to_header, instance_to_line
from core.decoradores import superuser_required
from empresas.forms import CrearTramo
from empresas.models import Tramo
#Imports de la app
from .models import Beneficiario, Documentacion, Domicilio, Info_Educativa
from .models import Credito, EventoCredito
from .forms import BuscarBeneficiario, IngresoBeneficiario
from .forms import BeneficiarioForm
from .forms import DocumentacionForm, DomicilioForm, InfoEducativaForm
from .forms import CreditoForm
from .functions import get_beneficiario, obtener_eventos_diferenciados
from .decoradores import validado_simple, validado_credito, validado_educativo

# Create your views here.
#cuando estan loggeados los administradores
def menu(request):
    beneficiario =  get_beneficiario(request)
    if beneficiario:
        return render(request, 'beneficiarios/panel_publico.html', {'beneficiario': beneficiario})
    elif request.user.has_perm('beneficiarios.menu'):
        return render(request, 'administradores/menu_administradores.html', {})
    else:
        return render(request, 'extras/error.html', {})

#Ingreso publico de beneficiarios >> DEBERIAMOS EVITAR REPETIR
def ingreso_beneficiario(request):
    if request.user.is_authenticated:
        try:
            beneficiario =  Beneficiario.objects.get(usuario=request.user)
            return menu(request)
        except Beneficiario.DoesNotExist:
            return render(request, 'extras/error.html', {})
    #Si no esta loggeado, lo mandamos por aca a que se loggee
    form = IngresoBeneficiario()
    if request.method == 'POST':
        form = IngresoBeneficiario(request.POST)
        if form.is_valid():
            login(request, form.user)
            beneficiario = form.beneficiario
            return render(request, 'beneficiarios/panel_publico.html', {'beneficiario': beneficiario, })
    return render(request, "extras/generic_form.html", {'titulo': 'Ingreso de Benficiarios', 'form': form, 'boton': 'Ingresar', })

@permission_required('beneficiarios.buscar_beneficiario')
def buscar_beneficiario(request):
    form = BuscarBeneficiario()
    if request.method == 'POST':
        form = BuscarBeneficiario(request.POST)
        if form.is_valid():
            beneficiario = form.beneficiario
            return redirect('beneficiarios:resumen', beneficiario_id=beneficiario.id)
    #Si todo falla o es la primera vez que entra
    return render(request, 'extras/generic_form.html', {
        'form': form, 'titulo': "Buscar Beneficiario", 'boton': "Buscar",})

def resumen(request, beneficiario_id):
    if request.user.has_perm('beneficiarios.buscar_beneficiario'):
        beneficiario = Beneficiario.objects.get(pk=beneficiario_id)
        return render(request, 'administradores/resumen.html', {'beneficiario': beneficiario, })
    else:
        beneficiario =  get_beneficiario(request)
        if beneficiario:
            return render(request, 'beneficiarios/panel_publico.html', {'beneficiario': beneficiario})
        else:
            return render(request, 'extras/error.html', {})

@permission_required('beneficiarios.baja_beneficiario')
def baja_beneficiario(request, beneficiario_id):
    beneficiario = Beneficiario.objects.get(pk=beneficiario_id)
    titulo = "Baja de Beneficiario"
    message = "Se procedera a dar de baja todos los creditos que tiene el beneficiario "
    message+= beneficiario.apellidos + ', ' + beneficiario.nombres
    #FALTA EL PROCESO DE BAJA
    return render(request, 'extras/confirmar.html', {
        'titulo': titulo, 
        'message': message,
        })

@permission_required('beneficiarios.ver_tarjeta')
def ver_tarjeta(request, beneficiario_id):
    beneficiario = Beneficiario.objects.get(pk=beneficiario_id)
    return render(request, 'administradores/tarjeta.html', {'beneficiario': beneficiario, })

@permission_required('beneficiarios.crear_beneficiario')
def crear_beneficiario(request):
    form = BeneficiarioForm()
    if request.method == "POST":
        form = BeneficiarioForm(request.POST, request.FILES)
        if form.is_valid():
            beneficiario = form.save()
            return redirect('beneficiarios:resumen', beneficiario_id=beneficiario.id)
    return render(request, 'extras/generic_form.html', {
        'form': form, 
        'titulo': 'Crear Beneficiario',
        'boton': 'Crear'})

@permission_required('beneficiarios.modificar_beneficiario')
def modificar_beneficiario(request, beneficiario_id):
    beneficiario = Beneficiario.objects.get(pk=beneficiario_id)
    form = BeneficiarioForm(instance=beneficiario)
    if request.method == 'POST':
        form = BeneficiarioForm(request.POST, request.FILES, instance=beneficiario)
        if form.is_valid():
            form.save()
            return redirect('beneficiarios:resumen', beneficiario_id=beneficiario.id)
    return render(request, 'extras/generic_form.html', {
        'form': form, 
        'titulo': 'Modificar Beneficiario',
        'boton': 'Modificar'})

@permission_required('beneficiarios.crear_beneficiario')
def crear_usuario_beneficiario(request, beneficiario_id):
    beneficiario = Beneficiario.objects.get(pk=beneficiario_id)
    beneficiario.save()
    return redirect('beneficiarios:resumen', beneficiario_id=beneficiario.id)

@permission_required('beneficiarios.crear_beneficiario')
def activar_usuario_benef(request, user_id):
    usuario = User.objects.get(pk=user_id)
    beneficiario = Beneficiario.objects.get(usuario=usuario)
    usuario.is_active = True
    usuario.save()
    return redirect('beneficiarios:resumen', beneficiario_id=beneficiario.id)

@permission_required('beneficiarios.crear_beneficiario')
def mod_password_beneficiario(request, user_id):
    usuario = User.objects.get(pk=user_id)
    beneficiario = Beneficiario.objects.get(usuario=usuario)
    form = ModPasswordForm(initial={'username': usuario.username, })
    if request.method == 'POST':
        form = ModPasswordForm(request.POST)
        if form.is_valid():
            usuario.password = make_password(form.cleaned_data['passwd1'])
            usuario.save()
            return redirect('beneficiarios:resumen', beneficiario_id=beneficiario.id)
    #Sea por ingreso o por salida:
    return render(request, "extras/generic_form.html", {'titulo': "Modificar Usuario", 'form': form, 'boton': "Modificar", })

@permission_required('beneficiarios.modificar_beneficiario')
def subir_documentacion(request, beneficiario_id):
    beneficiario = Beneficiario.objects.get(pk=beneficiario_id)
    form = DocumentacionForm(initial={'beneficiario': beneficiario,})
    if request.method == 'POST':
        form = DocumentacionForm(request.POST, request.FILES)
        if form.is_valid():
            documento = form.save(commit=False)
            documento.beneficiario = beneficiario
            documento.fecha = date.today()
            documento.activa = False
            documento.save()
            return redirect('beneficiarios:resumen', beneficiario_id=beneficiario.id)
    #Si no lo subimos o es el primer ingreso terminamos aca
    return render(request, 'extras/generic_form.html', {
        'form': form, 
        'titulo': 'Subir Documento',
        'boton': 'Subir'})

@permission_required('beneficiarios.modificar_beneficiario')
def subir_fotografia(request, beneficiario_id):
    beneficiario = Beneficiario.objects.get(pk=beneficiario_id)
    form = UploadFotoForm(initial={'beneficiario': beneficiario,})
    if request.method == 'POST':
        form = UploadFotoForm(request.POST, request.FILES)
        if form.is_valid():
            beneficiario.fotografia = form.cleaned_data['imagen']
            beneficiario.save()
            return redirect('beneficiarios:resumen', beneficiario_id=beneficiario.id)
    return render(request, 'extras/generic_form.html', {
        'form': form, 
        'titulo': 'Subir Fotografia',
        'boton': 'Subir'})

@permission_required('beneficiarios.modificar_beneficiario')
def modificar_domicilios(request, beneficiario_id):
    beneficiario = Beneficiario.objects.get(pk=beneficiario_id)
    form = DomicilioForm(initial={'beneficiario': beneficiario})
    #Si tiene datos los precargamos
    if beneficiario.domicilio_actual():
        form = DomicilioForm(instance=beneficiario.domicilio_actual())
    #Si esta enviando datos
    if request.method == 'POST':
        form = DomicilioForm(request.POST)
        if form.is_valid():
            dom = form.save(commit=False)
            dom.id = None
            dom.fecha = timezone.now()
            dom.save()
            return redirect('beneficiarios:resumen', beneficiario_id=beneficiario.id)
    return render(request, 'extras/generic_form.html', {
        'form': form, 
        'titulo': 'Modificar Domicilio',
        'boton': 'Guardar'})

@validado_educativo('beneficiarios.buscar_beneficiario')
def historico_educativo(request, educativa_id):
    info_educativa = Info_Educativa.objects.get(pk=educativa_id)
    beneficiario = info_educativa.beneficiario
    establecimiento = info_educativa.establecimiento

begup/beneficiarios/templates/generic/creditos.html
{% block content %}
    <div class="row">
    <h2>
        <b>Creditos</b>
        {% if beneficiario.creditos_vencidos %}
            <a href="{% url 'beneficiarios:historial_creditos' beneficiario_id=beneficiario.id %}">
                <img class="icons" src="/static/img/icons/history.png" alt="Ver Historial">
            </a>
        {% endif %}
    </h2>
    {% if beneficiario.creditos_pedidos or beneficiario.creditos_actuales %}
            {% for credito in beneficiario.creditos_pedidos %}
                <div class="col-md-4">
                    <a class="nolink" href="{% url 'beneficiarios:ver_credito' credito_id=credito.id %}">
                        <div class="recuadro">
                            <p><b>Tramo:</b> {{credito.tramo}}</p>
                            <p><b>Boletos Pedidos:</b> {{credito.credito_total}}</p>
                            <p><b>Estado:</b> {{credito.estado_str}}</p>
                            <p><b>Fecha Pedido:</b> {{credito.fecha_pedido}}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
            {% for credito in beneficiario.creditos_actuales %}
                <div class="col-md-4">
                    <a class="nolink" href="{% url 'beneficiarios:ver_credito' credito_id=credito.id %}">
                        <div class="recuadro">
                            <p><b>Tramo:</b> {{credito.tramo}}</p>
                            <p><b>Boletos Disponibles::</b> {{credito.credito_actual}}</p>
                            <p><b>Estado:</b> {{credito.estado_str}}</p>
                            <p><b>Fecha Aprobado:</b> {{credito.fecha_aprobado}}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
    {% endif %}
    </div>
    <hr>
{% endblock %}

begup/beneficiarios/templates/generic/datos_beneficiario.html
{% load static %}
{% block content %}
    <h3><b>Datos Personales</b></h3>
    <p><b>Numero de Beneficiario:</b> {{beneficiario.num_benef}}</p>
    <p><b>Tipo de Beneficiario:</b> {{beneficiario.get_tipo_benef_display}}</p>    
    {% if beneficiario.usuario %}
        <p><b>Usuario:</b>
            {{beneficiario.usuario.username}}
            {% if beneficiario.usuario.is_active is not True %}
                <a class="nolink" href="{% url 'beneficiarios:activar_usuario_benef' user_id=beneficiario.usuario.id %}">
                    <img class="icons" src="{% static 'img/icons/unlock.png' %}" alt="Usuario Bloqueado">
                </a>              
            {% endif %}
            {% if perms.beneficiarios.modificar_password %}
                <a class="nolink" href="{% url 'beneficiarios:mod_password_beneficiario' user_id=beneficiario.usuario.id %}">
                    <img class="icons" src="{% static 'img/icons/changepassword.png' %}" alt="Cambiar Contraseña">
                </a>
            {% endif %}
        <p>
    {% else %}
        <p>
            <a class="nolink" href="{% url 'beneficiarios:crear_usuario_beneficiario' beneficiario_id=beneficiario.id %}">
                Crear Usuario
                <img class="icons" src="{% static 'img/icons/add_role.png' %}">
            </a>
        </p>
    {% endif %}
    <p><b>Numero de Documento:</b> {{beneficiario.num_doc}}</p>
    <p><b>Fecha De Nacimiento:</b> {{beneficiario.fecha_nacimiento}}</p>
    <p><b>Domicilio:</b> {{beneficiario.domicilio_actual}}</p>
    <p><b>Establecimiento Actual:</b> {{beneficiario.escuela_actual.nombre}}</p>
    <p><b>Telefono:</b> {{beneficiario.telefono}}</p>
    <p><b>Email: </b><a href="mailto:{{beneficiario.email}}" target="_blank">{{beneficiario.email}}</a></p>
{% endblock %}

begup/beneficiarios/templates/generic/datos_educativos.html
{% block content %}
    {% if beneficiario.info_educativa_actual %}
        <div class="row">
            <h2><b>Historial Academico</b></h2>
            {% for escolar in beneficiario.info_educativa_diferente %}
                <div class="col-md-4">
                    <div class="recuadro">
                        <p><b>Establecimiento:</b> {{escolar.establecimiento.nombre}}</p>
                        <p><b>Nivel:</b> {{escolar.get_nivel_display}}</p>
                        <p><b>Grado:</b> {{escolar.get_grado_display}}</p>
                        <p><b>Fecha:</b> {{escolar.fecha}}</p>
                        <p>
                            <b>Materias Aprobadas</b> 
                            {{escolar.materias_aprobadas}}
                            <a href="{% url 'beneficiarios:historico_educativo' educativa_id=escolar.id %}">(Ver historico)</a>
                        </p>
                    </div>
                </div>
            {% endfor %}
        </div>
        <hr>
    {% endif %}
{% endblock %}

begup/beneficiarios/templates/generic/documentos.html
{% block content %}
    {% if beneficiario.documentos.all %}
        <div class="row">
            <h2><b>Documentacion</b></h2>
            {% for documento in beneficiario.documentos.all %}
                <div class="col-md-4 recuadro">
                    <div class="col-md-4">
                        <b>{{documento.tipo.nombre}}</b>
                        <p><b>Fecha:</b> {{documento.fecha}}</p>
                        <p>
                            <b>Estado: </b>
                            {% if documento.activa %}
                                Activo
                            {% else %}
                                Pendiente
                                {% if perms.beneficiarios.ver_docs_pendientes %}
                                    <a href="{% url 'beneficiarios:activar_doc' doc_id=documento.id %}">
                                        <br>(Activar)
                                    </a>
                                {% endif %}
                                {% if perms.beneficiarios.ver_docs_pendientes %}
                                    <a href="{% url 'beneficiarios:eliminar_doc' doc_id=documento.id %}">
                                        <br>(Eliminar)
                                    </a>
                                {% endif %}
                            {% endif %}
                        </p>
                    </div>
                    <div class="col-md-8">
                        <a href="{{documento.archivo.url}}" target="_blank">
                            <img class="documento" src="{{documento.archivo.url}}" target="_blank">
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
        <hr>
    {% endif %}
{% endblock %}

begup/beneficiarios/templates/generic/foto_beneficiario.html
{% load static %}
{% block content %}
    {% if beneficiario.fotografia %}
        <img class="retrato" src="{{beneficiario.fotografia.url}}" alt="(foto)">
    {% else %}
        <img class="retrato" src="{% static '/img/nofoto.png' %}" alt="(foto)">
    {% endif %}
{% endblock %}

begup/beneficiarios/templates/generic/historico_educativo.html
{% extends 'base_beneficiarios.html' %}
{% load static %}
{% block content %}
    <div class="beneficiario container">
        <div class="row">
            <h2>
                <b>{{beneficiario.apellidos}}, {{beneficiario.nombres}}</b>
            </h2>
        </div>
        <div class="row">
            <div class="col-md-8">
                <div class="col-md-4">
                    {% include 'generic/foto_beneficiario.html' %}
                </div>
                <div class="col-md-8">
                    {% include 'generic/datos_beneficiario.html' %}
                </div>
            </div>
        </div>

        <div class="row">
            <h2><b>Historial Academico</b></h2>
            <p><b>Establecimineto:</b> {{establecimiento.nombre}}</b>
            {% for escolar in historicos %}
                <div class="col-md-4">
                    <div class="recuadro">
                        <p><b>Fecha:</b> {{escolar.fecha}}</p>
                        <p><b>Nivel:</b> {{escolar.get_nivel_display}}</p>
                        <p><b>Grado:</b> {{escolar.get_grado_display}}</p>
                        <p><b>Materias Aprobadas</b> {{escolar.materias_aprobadas}}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
{% endblock %}