begup/begup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
#Import Extras
import debug_toolbar

#Definimos todas nuestra roots:
urlpatterns = [
    #Standard
    path('admin/', admin.site.urls),

    #Admin-User Paths
    url(r'^login/$',auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),

    #Extras
    url(r'^tinymce/', include('tinymce.urls')),
    #path('backup/', include('backups.urls', namespace='bkups')),

    #Debug:
    path('__debug__/', include(debug_toolbar.urls)),

    #Apps:
    path('', include('core.urls')),
    path('georef/', include('georef.urls')),
    path('noticias/', include('noticias.urls')),
    path('beneficiarios/', include('beneficiarios.urls')),
    path('empresas/', include('empresas.urls')),
    path('establecimientos/', include('establecimientos.urls')),
    path('contenidos/', include('contenidos.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

begup/beneficiarios/urls.py
#Imports Django
from django.urls import path
from django.conf.urls import url
#Imports de la app
from . import views

app_name = 'beneficiarios'
urlpatterns = [
    #Home
    path('', views.menu, name='menu'),
    #Basicas del menu administrativo
    path('buscar/', views.buscar_beneficiario, name='buscar_beneficiario'),
    path('crear/', views.crear_beneficiario, name='crear_beneficiario'),
    path('resumen/<int:beneficiario_id>', views.resumen, name='resumen'),
    path('tarjeta/<int:beneficiario_id>', views.ver_tarjeta, name='ver_tarjeta'),
    path('modificar/<int:beneficiario_id>', views.modificar_beneficiario, name='modificar_beneficiario'),
    path('baja/<int:beneficiario_id>', views.baja_beneficiario, name='baja_beneficiario'),
    path('subir_foto/<int:beneficiario_id>', views.subir_fotografia, name='subir_fotografia'),
    path('crear_user/<int:beneficiario_id>',  views.crear_usuario_beneficiario, name='crear_usuario_beneficiario'),
    path('modpasswd/<int:user_id>',  views.mod_password_beneficiario, name='mod_password_beneficiario'),
    path('act_user/<int:user_id>',  views.activar_usuario_benef, name='activar_usuario_benef'),
    #Mod info
    path('mod_domicilios/<int:beneficiario_id>', views.modificar_domicilios, name='modificar_domicilios'),
    path('mod_educativa/<int:beneficiario_id>', views.modificar_info_educativa, name='modificar_info_educativa'),
    path('edu/historico/<int:educativa_id>', views.historico_educativo, name='historico_educativo'),
    #Manejo documentos
    path('documentos_pendientes', views.documentos_pendientes, name='documentos_pendientes'),
    path('docs/subir/<int:beneficiario_id>', views.subir_documentacion, name='subir_documentacion'),
    path('docs/activar/<int:doc_id>', views.activar_doc, name='activar_doc'),
    path('eliminar_doc/<int:doc_id>', views.eliminar_doc, name='eliminar_doc'),
    #Manejo de Creditos
    path('credito/pendientes', views.creditos_pendientes, name='creditos_pendientes'),
    path('credito/<int:credito_id>', views.ver_credito, name='ver_credito'),
    path('credito/historial/<int:beneficiario_id>', views.historial_creditos, name='historial_creditos'),
    path('credito/crear/<int:beneficiario_id>', views.crear_credito, name='crear_credito'),
    path('credito/editar/<int:credito_id>', views.editar_credito, name='editar_credito'),
    path('credito/aprobar/<int:credito_id>', views.aprobar_credito, name='aprobar_credito'),
    path('credito/eliminar/<int:credito_id>', views.baja_credito, name='eliminar_credito'),
    path('credito/baja/<int:credito_id>', views.baja_credito, name='baja_credito'),
    #Manejo de Tramos
    path('tramos/', views.lista_tramos, name='lista_tramos'),
    path('tramos/<int:tramo_id>', views.ver_tramo, name='ver_tramo'),
    path('tramos/crear/', views.crear_tramo, name='crear_tramo'),
    path('tramos/eliminar/<int:tramo_id>', views.eliminar_tramo, name='eliminar_tramo'),
    #Area de Beneficiarios
    path('pub/ingreso/', views.ingreso_beneficiario, name='ingreso_beneficiario'),
    path('pub_crear_credito/<int:beneficiario_id>', views.crear_credito, name='pub_crear_credito'),
    #path('pub_subir_documentacion/<int:beneficiario_id>', views.subir_documentacion, name='pub_subir_documentacion'),
    #path('pub_mod_beneficiario/<int:beneficiario_id>', views.modificar_beneficiario, name='pub_mod_beneficiario'),
    #path('pub_mod_domicilios/<int:beneficiario_id>', views.modificar_domicilios, name='pub_mod_domicilios'),
    #path('pub_mod_info_educativa/<int:beneficiario_id>', views.modificar_info_educativa, name='pub_mod_info_educativa'),
    #path('pub_subir_fotografia/<int:beneficiario_id>', views.subir_fotografia, name='pub_subir_fotografia'),
    #REPORTES
    path('rep/tarjetas/', views.tarjetas_impresas, name='tarjetas_impresas'),
    path('rep/creditos/', views.reporte_creditos, name='reporte_creditos'),
    url(r'down/creditos/(?P<begda>\d{4}-\d{2}-\d{2})/(?P<endda>\d{4}-\d{2}-\d{2})', views.download_creditos, name='download_creditos'),
    url(r'down/tarjetas/(?P<begda>\d{4}-\d{2}-\d{2})/(?P<endda>\d{4}-\d{2}-\d{2})', views.download_tarjetas, name='download_tarjetas'),
    #Carga Masiva
    path('upload', views.upload_beneficiarios, name='upload_beneficiarios'),
]

begup/core/urls.py
#Imports de Django
from django.conf.urls import url
from django.urls import path
#Imports de la app
from . import views
from . import autocomplete

#Definimos nuestros Paths
app_name = 'core'
urlpatterns = [
    #Home
    url(r'^$', views.home, name='home'),
    path('faqs', views.faqs, name='faqs'),
    path('contacto', views.contacto, name='contacto'),
    
    #Acceso de usuarios
    path('login', views.home_login, name='home_login'),
    path('logout', views.home_logout, name='home_logout'),
    
    #Administracion de usuarios
    path('user/admin_usuarios/<str:app_name>', views.admin_usuario, name='admin_usuario'),
    path('user/crear_usuario/<str:app_name>', views.crear_usuario, name='crear_usuario'),
    path('user/mod_usuario/<str:app_name>/<int:admin_id>', views.modificar_usuario, name='modificar_usuario'),
    path('user/mod_password/<str:app_name>/<int:user_id>', views.cambiar_password, name='cambiar_password'),
    path('user/des_user/<str:app_name>/<int:user_id>', views.desactivar_usuario, name='desactivar_usuario'),
    path('user/act_user/<str:app_name>/<int:user_id>', views.activar_usuario, name='activar_usuario'),
    
    #Administrar Roles
    path('grupos/<str:app_name>', views.configurar_grupos, name='configurar_grupos'),
    path('grupos/<str:app_name>/add', views.crear_grupo, name='crear_grupo'),
    path('grupos/<str:app_name>/delete/<int:grupo_id>', views.delete_grupo, name='delete_grupo'),

    #Auditoria
    path('auditoria', views.auditoria, name='auditoria'),
    path('auditoria/<int:user_id>', views.auditoria, name='auditoria_propia'),
    path('auditar/obj/<int:content_id>/<int:object_id>', views.auditar_cambios, name='auditar_cambios'),

    #Validaciones:
    url(r'^act_usuario/(?P<usuario_id>[0-9]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activar_usuario_mail, name='activar_usuario_mail'),
    url(r'^act_consulta/(?P<consulta_id>[0-9]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activar_consulta, name='activar_consulta'),
    
    #Autocomplete
    url(r'^usuarios-autocomplete/$', autocomplete.UsuariosAutocomplete.as_view(), name='usuarios-autocomplete',),

    #Web Services
    path('ws/', views.ws, name='ws'),
    path('ws/<str:nombre_app>/<str:nombre_modelo>/', views.ws, name='ws'),
]

begup/establecimientos/urls.py
#Imports django
from django.conf.urls import url
from django.urls import path
from django.contrib.auth.decorators import permission_required
#Imports de la app
from . import views
from . import autocomplete

app_name = 'establecimientos'
urlpatterns = [
    #Menu Basico
    path('', views.menu, name='menu_establecimientos'),
    #Crear Establecimiento
    path('listado/', views.listado_establecimientos, name='listado_establecimientos'),
    path('ver/<int:establecimiento_id>', views.ver_establecimiento, name='ver_establecimiento'),
    path('ver_alumnos/estab/<int:establecimiento_id>', views.ver_alumnos, name='ver_alumnos_establecimiento'),

    #ABMS:
    path('crear/', permission_required('establecimientos.crear_establecimientos')(views.crear_establecimiento), name='crear_establecimiento'),
    path('mod/<int:establecimiento_id>',permission_required('establecimientos.modificar_establecimientos')(views.crear_establecimiento), name='mod_establecimiento'),
    path('eliminar/<int:establecimiento_id>', views.eliminar_establecimiento, name='eliminar_establecimiento'),

    path('crear_sede/<int:establecimiento_id>', views.crear_sede, name='crear_sede'),
    path('ver_sede/<int:sede_id>', views.ver_sede, name='ver_sede'),
    path('mod_sede/<int:sede_id>', views.crear_sede, name='mod_sede'),
    path('eliminar_sede/<int:sede_id>', views.eliminar_sede, name='eliminar_sede'),
    
    path('crear_telefono/<int:establecimiento_id>', views.crear_telefono, name='crear_telefono'),
    path('mod_telefono/<int:telefono_id>', views.crear_telefono, name='mod_telefono'),
    path('eliminar_telefono/<int:telefono_id>', views.eliminar_telefono, name='eliminar_telefono'),

    path('crear_directivo/<int:establecimiento_id>', views.crear_directivo, name='crear_directivo'),
    path('mod_directivo/<int:directivo_id>', views.crear_directivo, name='mod_directivo'),
    path('eliminar_directivo/<int:directivo_id>', views.eliminar_directivo, name='eliminar_directivo'),

    path('crear_carrera/<int:establecimiento_id>', permission_required('establecimientos.crear_carrera')(views.crear_carrera), name='crear_carrera'),
    path('mod_carrera/<int:carrera_id>', permission_required('establecimientos.modificar_carrera')(views.crear_carrera), name='mod_carrera'),
    path('eliminar_carrera/<int:carrera_id>', views.eliminar_carrera, name='eliminar_carrera'),

    #SUPER ADMIN
    path('crear_admin', views.crear_administrador, name='crear_administrador'),
    path('upload', views.upload_establecimientos, name='upload_establecimientos'),

    #Autocomplete
    url(r'^establecimiento-autocomplete/$', autocomplete.EstablecimientoAutocomplete.as_view(), name='establecimiento-autocomplete',),
    url(r'^carrera-autocomplete/$', autocomplete.CarreraAutocomplete.as_view(), name='carrera-autocomplete',),
]

begup/establecimientos/forms.py
#imports python
#Imports Django
from django import forms
from django.contrib.auth.models import User
from django.forms.widgets import CheckboxSelectMultiple
#Imports Extras
from dal import autocomplete
#Imports de la app
from .models import Edu_Comun, Edu_Especial, Edu_Adultos
from .models import Establecimiento
from .models import Sede, Carrera, Telefono, Directivo

#Definimos nuestros forms
class CrearAdministradorEstablecimientos(forms.Form):
    establecimiento = forms.ModelChoiceField(
        label='Establecimiento', 
        queryset=Establecimiento.objects.all(), 
        widget=autocomplete.ModelSelect2(url='establecimientos:establecimiento-autocomplete'))
    username = forms.CharField(label='Usuario', max_length=15, min_length=6)
    nombre = forms.CharField(label='Nombre', max_length=50)
    apellido = forms.CharField(label='Apellido', max_length=50)
    email = forms.EmailField(label='Email', max_length=50)
    grupos = forms.MultipleChoiceField(
        label='Grupos',
        widget=CheckboxSelectMultiple(attrs={'class':'multiplechoice',}),
    )
    def __init__(self, *args, **kwargs):
        group_list = kwargs.pop('group_list', None)
        if group_list:
            self.base_fields['grupos'].choices = group_list.values_list('id', 'name')
        super(CrearAdministradorEstablecimientos, self).__init__(*args, **kwargs)
    def clean_username(self):
        if not hasattr(self, 'instance') and User.objects.filter(username=self.cleaned_data['username']):
            raise forms.ValidationError("El usuario indicado ya esta en uso, si el usuario tiene mas de una funcion, contacte al administrador")
        return self.cleaned_data['username']
    def clean_email(self):
        if not hasattr(self, 'instance') and User.objects.filter(email=self.cleaned_data['email']):
            raise forms.ValidationError("El mail indicado ya esta en uso, si el usuario tiene mas de una funcion, contacte al administrador")
        return self.cleaned_data['email']

class EstablecimientoForm(forms.ModelForm):
    edu_comun = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=Edu_Comun.objects.all(), required=False)
    edu_especial = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=Edu_Especial.objects.all(), required=False)
    edu_adultos = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=Edu_Adultos.objects.all(), required=False)
    class Meta:
        model = Establecimiento
        fields= '__all__'

class SedeForm(forms.ModelForm):
    class Meta:
        model = Sede
        fields= '__all__'
        exclude = ('gps_point', 'fecha', 'activa')
        widgets = {
            'localidad': autocomplete.ModelSelect2(url='georef:localidad-autocomplete'),
            'barrio': autocomplete.ModelSelect2(url='georef:barrio-autocomplete'),
        }
    def __init__(self, *args, **kwargs):
        super(SedeForm, self).__init__(*args, **kwargs)
        self.fields['establecimiento'].widget.attrs['readonly'] = True

class CarreraForm(forms.ModelForm):
    class Meta:
        model = Carrera
        fields= '__all__'
        exclude = ('activa', 'fecha', )
    def __init__(self, *args, **kwargs):
        super(CarreraForm, self).__init__(*args, **kwargs)
        self.fields['sede'].widget.attrs['readonly'] = True

class TelefonoForm(forms.ModelForm):
    class Meta:
        model = Telefono
        fields= '__all__'
        exclude = ('activo', 'fecha', )

class DirectivoForm(forms.ModelForm):
    class Meta:
        model = Directivo
        exclude = ('activo', 'fecha', )

begup/establecimientos/templates/base_establecimientos.html
{% extends 'base/base.html' %}

{% load static %}

{% block custom_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/establecimientos.css' %}" />
{% endblock %}

{% block content %}

{% endblock %}

{% block custom_script %}

{% endblock %}

begup/establecimientos/templates/info_directivo.html
{% load static %}
{% block content %}
    <p>
        <b>Nombre: {{directivo.apellidos}}, {{directivo.nombres}}</b>
        {% if perms.establecimientos.crear_directivo %}
            <a class="nolink" href="{% url 'establecimientos:mod_directivo' directivo_id=directivo.id %}">
                <img class="icons" src="{% static '/img/icons/change.png' %}">
            </a>
        {% endif %}
        {% if perms.establecimientos.eliminar_directivo %}
            <a class="nolink" href="{% url 'establecimientos:eliminar_directivo' directivo_id=directivo.id %}">
                <img class="icons" src="{% static '/img/icons/delete.png' %}">
            </a>
        {% endif %}
    </p>
    <p>Documento de identidad: {{directivo.num_doc}}</p>
    <p>Domicilio: {{directivo.domicilio}}</p>
    <p>Telefono: {{directivo.telefono}}</p>
    <p>Email: {{directivo.email}}</p>
{% endblock %}

begup/establecimientos/templates/info_telefono.html
{% load static %}
{% block content %}
    <li>
        {{telefono.prefijo}} - {{telefono.cod_area}} - {{telefono.telefono}}
        {% if perms.establecimientos.modificar_establecimientos %}
            <a class="nolink" href="{% url 'establecimientos:mod_telefono' telefono_id=telefono.id %}">
                <img class="icons" src="{% static '/img/icons/change.png' %}">
            </a>
        {% endif %}
        {% if perms.establecimientos.modificar_establecimientos %}
            <a class="nolink" href="{% url 'establecimientos:eliminar_telefono' telefono_id=telefono.id %}">
                <img class="icons" src="{% static '/img/icons/delete.png' %}">
            </a>    
        {% endif %}
    </li>
{% endblock %}

begup/establecimientos/templates/listado_establecimientos.html
{% extends 'base_establecimientos.html' %}
{% load static %}
{% block content %}
    <div class="beneficiario container">
        <div class="row">
            <h2><b>Listado de Establecimientos</b></h2>
            {% include 'extras/buscador.html' %}
        </div>
        <div class="row">
            <div class="col-md-12">
                <table class="listado">
                    <tr>
                        <th>CUE</th>
                        <th>CueAnexo</th>
                        <th>Nombre</th>
                        <th>Sector</th>
                        <th>Ambito</th>
                        <th>Localidad</th>
                        <th>Ver Panel</th>
                    </tr>
                    {% for estab in establecimientos %}
                        <tr>
                            <td>{{estab.cue}}</td>
                            <td>{{estab.cueanexo}}</td>
                            <td>{{estab.nombre}}</td>
                            <td>{{estab.get_sector_display}}</td>
                            <td>{{estab.get_ambito_display}}</td>
                            <td>{{estab.localidad}}</td>
                            <td>
                                <a class="nolink" href="{% url 'establecimientos:ver_establecimiento' establecimiento_id=estab.id %}">
                                    <img class="icons" src="{% static '/img/icons/history.png' %}" alt="Ver Informacion Ampliada">
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
                {% include 'extras/paginador.html' with elementos=establecimientos %}
            </div>
        </div>
    </div>
{% endblock %}

begup/establecimientos/templates/menu_establecimientos.html
{% extends 'base_establecimientos.html' %}
{% load seguridad_tags%}
{% load establecimientos_tags%}
{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">
                    <h1>Menu Establecimiento:</h1>
                    <div class="col-md-8">
                        <ul class="menu_botones">
                            {% if perms.establecimientos.buscar_establecimientos %}
                                <li><a href="{% url 'establecimientos:listado_establecimientos' %}">Listado de Establecimientos</a></li>
                            {% endif %}
                            {% if perms.establecimientos.crear_establecimientos %}
                                <li><a href="{% url 'establecimientos:crear_establecimiento' %}">Crear Establecimiento</a></li>
                            {% endif %}
                            {% if perms.establecimientos.administrador %}
                                <li><a href="{% url 'core:admin_usuario' app_name='Establecimientos' %}">Administrar Usuarios</a></li>
                            {% endif %}
                            
                            {% if request.user.is_superuser %}
                                <li><a href="{% url 'establecimientos:crear_administrador' %}">Crear Administrador</a></li>
                                <li><a href="{% url 'core:configurar_grupos' app_name='Establecimientos' %}">Configurar Roles</a></li>
                            {% endif %}
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <p>Informacion del usuario:<b> {{request.user.username}}</b></p>
                        <p>Establecimiento:<b> {% ct_get_establecimiento request.user %}</b></p>
                        <p>Roles del usuario:</p>
                        <ul>
                            {% ct_get_grupos request.user as grupos %}
                            {% for grupo in grupos %}
                                <li>{{grupo.name}}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

begup/establecimientos/templates/opciones_carrera.html
{% block content %}
    <h2><b>Opciones:</b></h2>
    <ul class="menu_botones">
        {% if perms.establecimientos.modificar_carrera %}
            <li><a href="{% url 'establecimientos:mod_carrera' carrera_id=carrera.id %}">
                Modificar Carrera
            </a></li>
        {% endif %}
        {% if perms.establecimientos.eliminar_carrera %}
            <li class="delete"><a href="{% url 'establecimientos:eliminar_carrera' carrera_id=carrera.id %}">
                Eliminar Carrera
            </a></li>
        {% endif %}
    </ul>
{% endblock %}

begup/establecimientos/templates/opciones_establecimiento.html
{% block content %}
    <h2><b>Opciones:</b></h2>
    <ul class="menu_botones">
        {% if perms.establecimientos.buscar_establecimientos %}
            <li><a href="{% url 'establecimientos:ver_alumnos_establecimiento' establecimiento_id=establecimiento.id %}">Ver Alumnos</a></li>
        {% endif %}
        {% if perms.establecimientos.modificar_establecimientos %}
            <li><a href="{% url 'establecimientos:mod_establecimiento' establecimiento_id=establecimiento.id %}">
                Modificar Datos Basicos
            </a></li>
        {% endif %}
        {% if perms.establecimientos.modificar_establecimientos %}
            <li><a href="{% url 'establecimientos:crear_sede' establecimiento_id=establecimiento.id %}">
                Agregar Sede
            </a></li>
        {% endif %}
        {% if perms.establecimientos.modificar_establecimientos %}
            <li><a href="{% url 'establecimientos:crear_telefono' establecimiento_id=establecimiento.id %}">
                Agregar Telefono
            </a></li>
        {% endif %}
        {% if perms.establecimientos.modificar_establecimientos %}
            <li><a href="{% url 'establecimientos:crear_directivo' establecimiento_id=establecimiento.id %}">
                Agregar Directivos
            </a></li>
        {% endif %}
        {% if perms.establecimientos.crear_carrera %}
            <li><a href="{% url 'establecimientos:crear_carrera' establecimiento_id=establecimiento.id %}">
                Agregar Carrera
            </a></li>
        {% endif %}
        {% if request.user.is_superuser %}
            <li class="delete"><a href="{% url 'establecimientos:eliminar_establecimiento' establecimiento_id=establecimiento.id %}">
                Eliminar Establecimiento
            </a></li>
        {% endif %}
    </ul>
{% endblock %}

begup/establecimientos/templates/opciones_sede.html
{% block content %}
    <h2><b>Opciones:</b></h2>
    <ul class="menu_botones">
        {% if perms.establecimientos.modificar_establecimientos %}
            <li><a href="{% url 'establecimientos:mod_sede' sede_id=sede.id %}">
                Modificar Sede
            </a></li>
        {% endif %}
        {% if perms.establecimientos.modificar_establecimientos %}
            <li><a href="{% url 'establecimientos:crear_telefono' establecimiento_id=sede.establecimiento.id %}">
                Crear Telefono
            </a></li>
        {% endif %}
        {% if perms.establecimientos.crear_carrera %}
            <li><a href="{% url 'establecimientos:crear_carrera' establecimiento_id=sede.establecimiento.id %}">
                Crear Carrera
            </a></li>
        {% endif %}
        {% if request.user.is_superuser %}
            <li class="delete"><a href="{% url 'establecimientos:eliminar_sede' sede_id=sede.id %}">
                Eliminar Sede
            </a></li>
        {% endif %}
    </ul>
{% endblock %}

begup/establecimientos/templates/ver_establecimiento.html
{% extends 'base_establecimientos.html' %}
{% load static %}
{% block content %}
    <div class="beneficiario container">
        <h2>
            {% if establecimiento.escudo %}
                <img class="escudo" src="{{establecimiento.escudo.url}}" alt="(foto)">
            {% else %}
                {% if perms.establecimientos.modificar_establecimientos %}
                    <a class="nolink" href="{% url 'establecimientos:mod_establecimiento' establecimiento_id=establecimiento.id %}">
                        <img class="escudo" src="{% static 'img/icons/add_pic.png' %}" alt="Agregar Escudo">
                    </a>
                {% endif %}
            {% endif %}
            <b>{{establecimiento.nombre}}</b>
        </h2>
        <br>
        <div class="row">
            <div class="row">
                <div class="col-sm-8">
                    <div class="col-md-6">
                        <p><b>CUE ANEXO:</b> {{establecimiento.cueanexo}}</p>
                        <p><b>CUE:</b> {{establecimiento.cue}}</p>
                        <p><b>Sector:</b> {{establecimiento.get_sector_display}}</p>
                        <p><b>Ambito:</b> {{establecimiento.get_ambito_display}}</p>
                        <p><b>Periodo:</b> {{establecimiento.get_periodo_display}}</p>
                        <p><b>Email:</b> {{establecimiento.email}}</p>
                        <p><b>Web:</b> {{establecimiento.web}}</p>
                        <p><b>Alumnos Cursando:</b> {{establecimiento.cantidad_alumnos}}</p>
                    </div>
                    <div class="col-md-6">
                        {% for edu in establecimiento.edu_comun.all %}
                            {% if forloop.first %}
                                Educacion Comun:</p>
                                <lu>
                            {% endif %}
                            <li>{{edu.nombre}}</li>
                            {% if forloop.last %}
                                </lu>
                            {% endif %}
                        {% endfor %}
                        {% for edu in establecimiento.edu_especial.all %}
                            {% if forloop.first %}
                                Educacion Especial</p>
                                <lu>
                            {% endif %}
                            <li>{{edu.nombre}}</li>
                            {% if forloop.last %}
                                </lu>
                            {% endif %}
                        {% endfor %}
                        {% for edu in establecimiento.edu_adultos.all %}
                            {% if forloop.first %}
                                <p>Educacion Adultos:</p>
                                <lu>
                            {% endif %}
                            <li>{{edu.nombre}}</li>
                            {% if forloop.last %}
                                </lu>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
                <div class="col-md-4">
                    {% include 'opciones_establecimiento.html' %}
                </div>
            </div>

            <div class="row">
                <hr>
                {% for sede in establecimiento.sedes_activas.all %}
                    <div class="col-sm-6">
                        <h2><b><a class="nolink" href="{% url 'establecimientos:ver_sede' sede_id=sede.id %}">{{sede.nombre}}</a></b></h2>
                        <p>Region: {{sede.get_region_display}}</p>
                        <p>Localidad: {{sede.localidad.nombre}}, Barrio: {{sede.barrio.nombre}}</p>
                        <p>Direccion: {{sede.calle}} {{sede.numero}}</p>
                        <br>
                        {% if sede.telefonos_activos %}
                            <p><b>Telefonos:</b></p>
                            <ul>
                                {% for telefono in sede.telefonos_activos.all %}
                                    {% include 'info_telefono.html' %}
                                {% endfor %}
                            </ul>
                            <br>
                        {% endif %}
                        {% if sede.carreras_activas %}
                            <ul>
                                {% for carrera in sede.carreras_activas %}
                                    <p><b>{{carrera.nombre}}</b></p>
                                    <p>Cantidad de Materias: {{carrera.cant_materias}}</p>
                                {% endfor %}
                            <ul>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
            {% if establecimiento.directivos_activos %}
                <hr>
                <div class="row">
                <h3><b>Directivos:</b></h3>
                    <div class="col-sm-4">
                        {% for directivo in  establecimiento.directivos_activos %}
                            {% include 'info_directivo.html' %}
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}