begup/begup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
#Import Extras
import debug_toolbar

#Definimos todas nuestra roots:
urlpatterns = [
    #Standard
    path('admin/', admin.site.urls),

    #Admin-User Paths
    url(r'^login/$',auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),

    #Extras
    url(r'^tinymce/', include('tinymce.urls')),
    #path('backup/', include('backups.urls', namespace='bkups')),

    #Debug:
    path('__debug__/', include(debug_toolbar.urls)),

    #Apps:
    path('', include('core.urls')),
    path('georef/', include('georef.urls')),
    path('noticias/', include('noticias.urls')),
    path('beneficiarios/', include('beneficiarios.urls')),
    path('empresas/', include('empresas.urls')),
    path('establecimientos/', include('establecimientos.urls')),
    path('contenidos/', include('contenidos.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

begup/beneficiarios/urls.py
#Imports Django
from django.urls import path
from django.conf.urls import url
#Imports de la app
from . import views

app_name = 'beneficiarios'
urlpatterns = [
    #Home
    path('', views.menu, name='menu'),
    #Basicas del menu administrativo
    path('buscar/', views.buscar_beneficiario, name='buscar_beneficiario'),
    path('crear/', views.crear_beneficiario, name='crear_beneficiario'),
    path('resumen/<int:beneficiario_id>', views.resumen, name='resumen'),
    path('tarjeta/<int:beneficiario_id>', views.ver_tarjeta, name='ver_tarjeta'),
    path('modificar/<int:beneficiario_id>', views.modificar_beneficiario, name='modificar_beneficiario'),
    path('baja/<int:beneficiario_id>', views.baja_beneficiario, name='baja_beneficiario'),
    path('subir_foto/<int:beneficiario_id>', views.subir_fotografia, name='subir_fotografia'),
    path('crear_user/<int:beneficiario_id>',  views.crear_usuario_beneficiario, name='crear_usuario_beneficiario'),
    path('modpasswd/<int:user_id>',  views.mod_password_beneficiario, name='mod_password_beneficiario'),
    path('act_user/<int:user_id>',  views.activar_usuario_benef, name='activar_usuario_benef'),
    #Mod info
    path('mod_domicilios/<int:beneficiario_id>', views.modificar_domicilios, name='modificar_domicilios'),
    path('mod_educativa/<int:beneficiario_id>', views.modificar_info_educativa, name='modificar_info_educativa'),
    path('edu/historico/<int:educativa_id>', views.historico_educativo, name='historico_educativo'),
    #Manejo documentos
    path('documentos_pendientes', views.documentos_pendientes, name='documentos_pendientes'),
    path('docs/subir/<int:beneficiario_id>', views.subir_documentacion, name='subir_documentacion'),
    path('docs/activar/<int:doc_id>', views.activar_doc, name='activar_doc'),
    path('eliminar_doc/<int:doc_id>', views.eliminar_doc, name='eliminar_doc'),
    #Manejo de Creditos
    path('credito/pendientes', views.creditos_pendientes, name='creditos_pendientes'),
    path('credito/<int:credito_id>', views.ver_credito, name='ver_credito'),
    path('credito/historial/<int:beneficiario_id>', views.historial_creditos, name='historial_creditos'),
    path('credito/crear/<int:beneficiario_id>', views.crear_credito, name='crear_credito'),
    path('credito/editar/<int:credito_id>', views.editar_credito, name='editar_credito'),
    path('credito/aprobar/<int:credito_id>', views.aprobar_credito, name='aprobar_credito'),
    path('credito/eliminar/<int:credito_id>', views.baja_credito, name='eliminar_credito'),
    path('credito/baja/<int:credito_id>', views.baja_credito, name='baja_credito'),
    #Manejo de Tramos
    path('tramos/', views.lista_tramos, name='lista_tramos'),
    path('tramos/<int:tramo_id>', views.ver_tramo, name='ver_tramo'),
    path('tramos/crear/', views.crear_tramo, name='crear_tramo'),
    path('tramos/eliminar/<int:tramo_id>', views.eliminar_tramo, name='eliminar_tramo'),
    #Area de Beneficiarios
    path('pub/ingreso/', views.ingreso_beneficiario, name='ingreso_beneficiario'),
    path('pub_crear_credito/<int:beneficiario_id>', views.crear_credito, name='pub_crear_credito'),
    #path('pub_subir_documentacion/<int:beneficiario_id>', views.subir_documentacion, name='pub_subir_documentacion'),
    #path('pub_mod_beneficiario/<int:beneficiario_id>', views.modificar_beneficiario, name='pub_mod_beneficiario'),
    #path('pub_mod_domicilios/<int:beneficiario_id>', views.modificar_domicilios, name='pub_mod_domicilios'),
    #path('pub_mod_info_educativa/<int:beneficiario_id>', views.modificar_info_educativa, name='pub_mod_info_educativa'),
    #path('pub_subir_fotografia/<int:beneficiario_id>', views.subir_fotografia, name='pub_subir_fotografia'),
    #REPORTES
    path('rep/tarjetas/', views.tarjetas_impresas, name='tarjetas_impresas'),
    path('rep/creditos/', views.reporte_creditos, name='reporte_creditos'),
    url(r'down/creditos/(?P<begda>\d{4}-\d{2}-\d{2})/(?P<endda>\d{4}-\d{2}-\d{2})', views.download_creditos, name='download_creditos'),
    url(r'down/tarjetas/(?P<begda>\d{4}-\d{2}-\d{2})/(?P<endda>\d{4}-\d{2}-\d{2})', views.download_tarjetas, name='download_tarjetas'),
    #Carga Masiva
    path('upload', views.upload_beneficiarios, name='upload_beneficiarios'),
]

begup/core/urls.py
#Imports de Django
from django.conf.urls import url
from django.urls import path
#Imports de la app
from . import views
from . import autocomplete

#Definimos nuestros Paths
app_name = 'core'
urlpatterns = [
    #Home
    url(r'^$', views.home, name='home'),
    path('faqs', views.faqs, name='faqs'),
    path('contacto', views.contacto, name='contacto'),
    
    #Acceso de usuarios
    path('login', views.home_login, name='home_login'),
    path('logout', views.home_logout, name='home_logout'),
    
    #Administracion de usuarios
    path('user/admin_usuarios/<str:app_name>', views.admin_usuario, name='admin_usuario'),
    path('user/crear_usuario/<str:app_name>', views.crear_usuario, name='crear_usuario'),
    path('user/mod_usuario/<str:app_name>/<int:admin_id>', views.modificar_usuario, name='modificar_usuario'),
    path('user/mod_password/<str:app_name>/<int:user_id>', views.cambiar_password, name='cambiar_password'),
    path('user/des_user/<str:app_name>/<int:user_id>', views.desactivar_usuario, name='desactivar_usuario'),
    path('user/act_user/<str:app_name>/<int:user_id>', views.activar_usuario, name='activar_usuario'),
    
    #Administrar Roles
    path('grupos/<str:app_name>', views.configurar_grupos, name='configurar_grupos'),
    path('grupos/<str:app_name>/add', views.crear_grupo, name='crear_grupo'),
    path('grupos/<str:app_name>/delete/<int:grupo_id>', views.delete_grupo, name='delete_grupo'),

    #Auditoria
    path('auditoria', views.auditoria, name='auditoria'),
    path('auditoria/<int:user_id>', views.auditoria, name='auditoria_propia'),
    path('auditar/obj/<int:content_id>/<int:object_id>', views.auditar_cambios, name='auditar_cambios'),

    #Validaciones:
    url(r'^act_usuario/(?P<usuario_id>[0-9]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activar_usuario_mail, name='activar_usuario_mail'),
    url(r'^act_consulta/(?P<consulta_id>[0-9]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activar_consulta, name='activar_consulta'),
    
    #Autocomplete
    url(r'^usuarios-autocomplete/$', autocomplete.UsuariosAutocomplete.as_view(), name='usuarios-autocomplete',),

    #Web Services
    path('ws/', views.ws, name='ws'),
    path('ws/<str:nombre_app>/<str:nombre_modelo>/', views.ws, name='ws'),
]

begup/empresas/urls.py
#Imports de Django
from django.urls import path
from django.conf.urls import url
#Imports de la app
from . import views
from . import autocomplete

app_name = 'empresas'
urlpatterns = [
    #Basicas del menu
    path('', views.menu, name='menu'),
    #Entrega de pasajes
    path('buscar/', views.buscar_credito, name='buscar_credito'),
    path('entrega/<int:id_codigo>', views.entregar_credito, name='entregar_credito'),
    #Costos
    path('costos/', views.lista_costos, name='lista_costos'),
    path('costos/<int:costo_id>', views.ver_costo, name='ver_costo'),
    path('costos/crear/', views.crear_costo, name='crear_costo'),
    path('costos/crear/<int:tramo_id>', views.crear_costo, name='crear_costo'),
    path('costos/actualizar/<int:costo_id>', views.crear_costo, name='actualizar_costo'),
    path('costos/desactivar/<int:costo_id>', views.desactivar_costo, name='desactivar_costo'),
    path('costos/fix/<int:costo_id>', views.fix_costo, name='fix_costo'),
    path('costos/del/<int:costo_id>', views.del_costo, name='del_costo'),
    #Reportes
    path('facturacion_diaria/', views.informe_diario, name='informe_diario'),
    path('facturacion_mensual/', views.facturacion_mensual, name='facturacion_mensual'),
    path('ver_facturacion/<int:factura_id>', views.ver_factura, name='ver_factura'),
    path('csv_facturacion/<int:factura_id>', views.csv_factura, name='csv_factura'),
    path('ver_facturacion/detalle/<int:detalle_id>', views.detalle_facturacion_mensual, name='detalle_facturacion_mensual'),
    path('del_facturacion/<int:factura_id>', views.eliminar_facturacion, name='eliminar_facturacion'),
    #SUPER ADMIN
    path('crear_admin', views.crear_administrador, name='crear_administrador'),
    path('upload', views.upload_empresas, name='upload_empresas'),

    #Autocompleteviews
    url(r'^empresa-autocomplete/$', autocomplete.EmpresaAutocomplete.as_view(), name='empresa-autocomplete',),
    url(r'^paraje-autocomplete/$', autocomplete.ParajeAutocomplete.as_view(), name='paraje-autocomplete',),
    url(r'^tramo-autocomplete/$', autocomplete.TramoAutocomplete.as_view(), name='tramo-autocomplete',),
]

begup/empresas/templates/base_empresa.html
{% extends 'base/base.html' %}
{% load static %}
{% block custom_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/empresas.css' %}" />
{% endblock %}

{% block content %}

{% endblock %}

{% block custom_script %}

{% endblock %}

begup/empresas/templates/comprobante.html
{% extends 'base_empresa.html' %}

{% block content %}
    <div class="container beneficiario">
        <br>
        <h3>Se autorizo y confirmo la entrega de pasajes para el beneficiario<h3>
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-5 informacion">
                <p><b>{{benef.get_tipo_benef_display}}:</b> N° {{benef.num_benef}}</p>
                <p><b>{{benef.get_tipo_doc_display}}</b> {{benef.num_doc}}</p>
                <p><b>Fecha de Nacimiento:</b> {{benef.fecha_nacimiento}}</p>
                <p><b>Telefono:</b> {{benef.telefono}}</p>
                <p><b>Email: </b>{{benef.email}}</p>
            </div>
            <div class="col-md-5 informacion">
                <p><b>Tramo:</b> {{credito.tramo}}</p>
                <p><b>Codigo Utilizado:</b> {{codigo.clave}} de {{codigo.porcentaje}}%</b>
                <p><b>Entregar: </b>{{consumo.cantidad}} Pasajes</b>
                <p><b>Fecha de Entrega:</b> {{evento.fecha}}</p>
            </div>
        </div>
        <a class="volver" href="{% url 'empresas:menu' %}">Volver al menu principal</a>
    </div>
{% endblock %}

begup/empresas/templates/consumir_credito.html
{% extends 'base_empresa.html' %}

{% block content %}
    <div class="container beneficiario">
        <h3><b>Credito para Entregar:</b></h3>
        <div class="row">
            <div class="col-md-4">
                <div class="credito">
                    <p><b>Tramo:</b> {{credito.tramo}}</p>
                    <p><b>Cantidad Total:</b> {{credito.credito_total}}</p>
                    <p><b>Cantidad Usada:</b> {{credito.credito_usado}}</p>
                    <p><b>Cantidad Disponible:</b> {{credito.credito_actual}}</p>
                </div>

                <div class="historico">
                    <p><b>HISTORICO</b></p>
                    {% for evento in credito.eventos.all %}
                        <p>{{evento.get_tipo_display}}: {{evento.fecha}}
                            {% if evento.tipo == 'C' %}
                                , Cantidad: {{evento.consumo.cantidad}} por 
                                {% if evento.consumo.empresa %}
                                    {{evento.consumo.empresa}}.
                                {% else %}
                                    Vencimiento.
                                {% endif %}
                            {% endif %}
                        </p>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-6">
                {% include "extras/generic_form-nobase.html" %}
            </div>
        </div>
    </div>
{% endblock %}

begup/empresas/templates/detalle_facturacion.html
{% extends 'base_empresa.html' %}
{% load humanize %}
{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">        
                    <h1>Detalle de Facturacion</h1>
                    <h2>{{empresa}}</h2>
                    <h2>Tramo: {{tramo}}</h2>
                    <h3><b>Periodo:</b> {{begda|date:'m/Y'}}</h3>
                    <div class="col-md-12">
                        <table class="listado" id="table">
                            <thead>
                                <tr>
                                    <th colspan="2">Beneficario</th>
                                    <th>Fecha</th>
                                    <th>Cantidad Pasajes</th>
                                    <th>Precio Pasaje</th>
                                    <th>Subtotal</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for evento in eventos %}
                                    <tr>
                                        {% with evento.credito.beneficiario as beneficiario %}
                                            <td>{{beneficiario.num_doc}}</td>
                                            <td>{{beneficiario.apellidos}}, {{beneficiario.nombres}}</td>
                                        {% endwith %}
                                        <td>{{evento.fecha}}</td>
                                        <td>{{evento.consumo.cantidad}}</td>
                                        <td>
                                            {{evento.consumo.costo}}
                                            {% if evento.consumo.actualizado %}
                                                <b>(Modificado Post-Consumo: {{evento.consumo.actualizado}})</b>
                                            {% endif %}
                                        </td>
                                        <td>{{evento.consumo.subtotal}}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

begup/empresas/templates/facturar.html
{% extends 'base_empresa.html' %}

{% load static %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                {% include "extras/generic_form-nobase.html" %}
            </div>

            <div class="col-md-5">
                <div class="historico">
                    <h3><b>Facturaciones Realizadas:</b></h3>
                    <ul>
                        {% for factura in facturas %}
                            <li>
                                {{factura}}
                                <a class="nolink" href="{% url 'empresas:ver_factura' factura_id=factura.id%}">
                                    <img class="icons" src="{% static '/img/icons/history.png' %}">
                                </a>
                                <a class="nolink"  href="{% url 'empresas:csv_factura' factura_id=factura.id%}">
                                    <img class="icons" src="{% static '/img/icons/download.png' %}">
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

begup/empresas/templates/informe_diario.html
{% extends 'base_empresa.html' %}
{% load humanize %}
{% load empresas_tags %}
{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">        
                    <h1>Informe Diario</h1>
                    {% if empresa %}<h2>{{empresa}}{% endif %}
                    <h3><b>Fecha:</b> {{fecha|date:'d/m/Y'}}</h3>
                    <div class="col-md-12">
                        <table class="listado" id="table">
                            <thead>
                                <tr>
                                    <th>Documento</th>
                                    <th>Beneficario</th>
                                    <th>Tramo</th>
                                    {% if not empresa %}<th>Empresa</th>{% endif %}
                                    <th>Cantidad Pasajes</th>
                                    <th>Valor</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for evento in eventos %}
                                    <tr>
                                        {% with evento.credito.beneficiario as beneficiario %}
                                            <td>{{beneficiario.num_doc}}</td>
                                            <td>{{beneficiario.apellidos}}, {{beneficiario.nombres}}</td>
                                        {% endwith %}
                                        <td>{{evento.credito.tramo}}</td>
                                        {% if not empresa %}<td>{{evento.consumo.empresa}}</td>{% endif %}
                                        <td>{{evento.consumo.cantidad}}</td>
                                        <td>{{evento.consumo.subtotal}}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                            <tr class="resultado">
                                <th colspan="{% if empresa %}3{% else %}4{% endif %}">Total</th>
                                <th>{% ct_sumar_pasajes eventos %}</th>
                                <th>{% ct_sumar_costo eventos %}</th>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

begup/empresas/templates/lista_costos.html
{% extends 'base_beneficiarios.html' %}

{% load static %}

{% block content %}
    <div class="beneficiario container">
        <div class="row">
            <h2><b>Costos Habilitados</b></h2>
            {% if empresa %}
                <h3>
                    Empresa: {{empresa.nombre}}
                </h3>
            {% endif %}
        </div>
        <div class="row">
            <div class="col-md-8">
                <table class="listado" id="table">
                    <thead>
                        <tr>
                            {% if not empresa %}
                                <th>Empresa</th>
                            {% endif %}
                            <th>Origen</th>
                            <th>Destino</th>
                            <th>Precio</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for costo in costos %}
                            <tr>
                                {% if not empresa %}
                                    <td>{{costo.empresa.nombre}}</td>
                                {% endif %}
                                <td>{{costo.tramo.origen}}</td>
                                <td>{{costo.tramo.destino}}</td>
                                <td>${{costo.precio}}</td>
                                <td>
                                    {% if perms.empresas.ver_costos or perms.beneficiarios.ver_costos%}
                                        <a class="nolink" href="{% url 'empresas:ver_costo' costo_id=costo.id %}">
                                            <img class="icons" src="{% static '/img/icons/history.png' %}" alt="Ver Historico">
                                        </a>
                                    {% endif %}
                                    {% if perms.empresas.crear_costos %}
                                        <a class="nolink" href="{% url 'empresas:actualizar_costo' costo_id=costo.id %}">
                                            <img class="icons" src="{% static '/img/icons/update.png' %}" alt="Actualizar Precio">
                                        </a>
                                        <a class="nolink" href="{% url 'empresas:desactivar_costo' costo_id=costo.id %}">
                                            <img class="icons" src="{% static '/img/icons/delete.png' %}" alt="Eliminar Costo">
                                        </a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-md-4">
                <h2><b>Opciones:</b></h2>
                <ul class="menu_botones">
                    {% if perms.empresas.crear_costos %}
                        <li><a href="{% url 'beneficiarios:crear_tramo' %}" target="_blank">Crear Nuevo Tramo</a></li>
                        <li><a href="{% url 'empresas:crear_costo' %}" target="_blank">Crear Nuevo Costo</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

begup/empresas/templates/menu_empresas.html
{% extends 'base_empresa.html' %}
{% load seguridad_tags%}
{% load empresas_tags%}
{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">        
                    <h1>Menu Empresas:</h1>
                    <div class="col-md-8">
                        <ul class="menu_botones">
                            {% if perms.empresas.entregar_credito %}
                                <li><a href="{% url 'empresas:buscar_credito'  %}">Entregar Pasajes</a></li>
                            {% endif %}
                            {% if perms.empresas.informe_diario %}
                                <li><a href="{% url 'empresas:informe_diario' %}">Informe Diario</a></li>
                            {% endif %}
                            {% if perms.empresas.facturacion_mensual %}
                                <li><a href="{% url 'empresas:facturacion_mensual' %}">Reporte de Facturacion Mensual</a></li>
                            {% endif %}
                            {% if perms.empresas.facturacion_mensual %}
                                <li><a href="{% url 'empresas:lista_costos' %}">Ver todos los costos Habilitados</a></li>
                            {% endif %}
                            {% if perms.empresas.administrador %}
                                <li><a href="{% url 'core:admin_usuario' app_name='Empresas' %}">Administrar Usuarios</a></li>
                            {% endif %}
                            {% if request.user.is_superuser %}
                                <li><a href="{% url 'empresas:crear_administrador' %}">Crear Administrador General</a></li>
                                <li><a href="{% url 'core:configurar_grupos' app_name='Empresas' %}">Configurar Roles</a></li>
                            {% endif %}
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <p>Informacion del usuario: <b>{{request.user.username}}</b></p>
                        <p>Empresa: <b>{% ct_get_empresa request.user %}</b></p>
                        <p>Roles del usuario:</p>
                        <ul>
                            {% ct_get_grupos request.user as grupos %}
                            {% for grupo in grupos %}
                                <li>{{grupo.name}}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

begup/empresas/templates/ver_costo.html
{% extends 'base_beneficiarios.html' %}

{% load static %}
{% load auditar_tags %}

{% block content %}
    <div class="beneficiario container">
        <div class="row">
            <h2>Empresa: {{costo.empresa}}</h2>
            <h2>Costo para: {{costo.tramo}}</h2>
        </div>
        <div class="row">
        <div class="col-md-12">
            <h3>Historico de Precios</h3>
            <div class="col-md-8">
                <table class="listado">
                    <tr>
                        <th>Fecha De Inicio</th>
                        <th>Fecha Vencimiento</th>
                        <th>Costo</th>
                    </tr>
                    {% for precio in costo.historico %}
                        <tr>
                            <td>{{precio.begda}}</td>
                            <td>{{precio.endda}}</td>
                            <td>
                                ${{precio.precio}}
                                <a class="nolink"  href="{% ct_auditar_obj_url precio %}">
                                    <img class="icons" src="{% static '/img/icons/question.png' %}">
                                </a>

                                {% if perms.empresas.reparar_costos %}
                                    <a class="nolink" href="{% url 'empresas:fix_costo' costo_id=precio.id %}">
                                        <img class="icons" src="{% static '/img/icons/change.png' %}" alt="Modificar Precio">
                                    </a>

                                    <a class="nolink" href="{% url 'empresas:del_costo' costo_id=precio.id %}">
                                        <img class="icons" src="{% static '/img/icons/delete.png' %}" alt="Eliminar Periodo">
                                    </a>

                                {% endif %}

                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
            <div class="col-md-4">
                <h2><b>Opciones:</b></h2>
                <ul class="menu_botones">
                    {% if perms.empresas.crear_costos %}
                        <li><a href="{% url 'empresas:actualizar_costo' costo_id=costo.id %}" target="_blank">Actualizar Precio</a></li>
                        <li class="delete"><a href="{% url 'empresas:desactivar_costo' costo_id=costo.id %}" target="_blank">Dar de Baja Tramo</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

begup/empresas/templates/ver_facturacion.html
{% extends 'base_empresa.html' %}

{% load static %}
{% load humanize %}
{% load empresas_tags %}

{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <h2>Reporte de Facturacion:</h2>
                <h3><b>Periodo:</b> {{begda|date:'m/Y'}}</h3>
                {% for factura in facturas %}
                    <div class="row">
                        {% if perms.beneficiarios.facturacion_admin %}
                            <a class="botoncito" href="{% url 'empresas:eliminar_facturacion' factura_id=factura.id  %}">
                                Eliminar Periodo de Facturacion
                                <img class="icons" src="{% static '/img/icons/delete.png' %}" alt="Eliminar Facturacion">
                            </a>
                        {% endif %}
                        <h1><b>Empresa:</b> {{factura.empresa.nombre}}</h1>
                        <div class="col-md-12">
                            <table class="listado" id="table">
                                <thead>
                                    <tr>
                                        <th>Tramo</th>
                                        <th>Cantidad Pasajes</th>
                                        <th>Importe</th>
                                        <th>Ver Detalle</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for detalle in factura.detalles.all %}
                                            <tr>
                                                <td>{{detalle.tramo}}</td>
                                                <td>{{detalle.cantidad}}</td>
                                                <td>{{detalle.subtotal}}</td>
                                                <td>
                                                    <a href="{% url 'empresas:detalle_facturacion_mensual' detalle_id=detalle.id %}" target="_blank">
                                                        (Ver Detalle)
                                                    </a>
                                                </td>
                                            </tr>
                                    {% endfor %}
                                </tbody>
                                <tr class="resultado">
                                    <td>Resultado</td>
                                    <td>{{factura.cantidad}}</td>
                                    <td colspan="2">{{factura.total}}</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <hr>
                {% endfor %}
            </div>
        </section>
    </section>
{% endblock %}